/* eslint-disable */
/* @ts-nocheck */

// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap } from "./routes.js";
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js";
import type React from "react";

/* ---------------------------------------------
   App Page Config Validation Types
---------------------------------------------- */

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default:
    | React.ComponentType<{ params: Promise<ParamMap[Route]> } & any>
    | ((
        props: { params: Promise<ParamMap[Route]> } & any
      ) =>
        | React.ReactNode
        | Promise<React.ReactNode>
        | never
        | void
        | Promise<void>);
  generateStaticParams?: (props: {
    params: ParamMap[Route];
  }) => Promise<any[]> | any[];
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any;
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any;
  metadata?: any;
  viewport?: any;
};

/* ---------------------------------------------
   Layout Config Validation Types
---------------------------------------------- */

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default:
    | React.ComponentType<LayoutProps<Route>>
    | ((
        props: LayoutProps<Route>
      ) =>
        | React.ReactNode
        | Promise<React.ReactNode>
        | never
        | void
        | Promise<void>);
  generateStaticParams?: (props: {
    params: ParamMap[Route];
  }) => Promise<any[]> | any[];
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any;
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any;
  metadata?: any;
  viewport?: any;
};

/* ---------------------------------------------
   Validate src/app/page.tsx
---------------------------------------------- */

{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific;

  // NOTE: Extensionless import is REQUIRED
  // Works for .ts / .tsx / .js / .jsx
  const handler = {} as typeof import("../src/app/page");

  type __Check = __IsExpected<typeof handler>;

  // Intentionally unused – type validation only
  type __Unused = __Check;
}

/* ---------------------------------------------
   Validate src/app/layout.tsx
---------------------------------------------- */

{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific;

  // NOTE: Extensionless import is REQUIRED
  const handler = {} as typeof import("../src/app/layout");

  type __Check = __IsExpected<typeof handler>;

  // Intentionally unused – type validation only
  type __Unused = __Check;
}